name: Code analysis

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Analyze code
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup SonarCloud
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.MinecraftToolBox }}

    - name: Analyze code with SonarCloud
      run: sonar-scanner

    - name: Upload coverage to SonarCloud
      uses: sonarsource/sonarcloud-github-action@master
      with:
        args: >
          -Dsonar.branch.name=sonarcloud
          -Dsonar.tests="${{ github.workspace }}/test-reports"
          -Dsonar.coverage.reportPaths="${{ github.workspace }}/coverage/lcov.info"
